[package]
name = "restest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
uuid = { version = "0.8", features = ["v4", "serde"]  }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
warp = "0.3"